app:
  apartment-names:
    - hauketo
    - grefsen
    - lorenskog
    - bjorndal
  file-storage:
    base-dir: ./data/expenses
    apartment: ./data/apartments
    tenant: ./data/tenants
server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:file:./data/testdb
    url: jdbc:h2:tcp://localhost:9092/./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    enable-spring-el-compiler: true

