logging:
  level:
    org.springframework.security: info

app:
  apartment-names:
    - hauketo
    - grefsen
    - lorenskog
    - bjorndal
  file-storage:
    base-dir: ./data/expenses
    apartment: ./data/apartments
    tenant: ./data/tenants
server:
  port: 8080
  servlet:
    session:
      timeout: 30m  # Session timeout set to 30 minutes


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Adjust based on your needs
      max-request-size: 10MB  # Adjust based on your needs
  web:
    resources:
      add-mappings: true
      chain:
        enabled: true
  datasource:
#    url: jdbc:h2:file:./data/testdb #use this ehen to deploy at rendor
    url: jdbc:h2:tcp://localhost:9092/./data/testdb;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    enable-spring-el-compiler: false

