app:
  apartment-names:
    - hauketo
    - grefsen
    - lorenskog
    - bjorndal
  file-storage:
    base-dir: ./data/expenses
    apartment: ./data/apartments

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    enable-spring-el-compiler: true
